/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FoodboxRouteImport } from './routes/foodbox'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicMpesaSimulateRouteImport } from './routes/api/public/mpesa/simulate'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodboxRoute = FoodboxRouteImport.update({
  id: '/foodbox',
  path: '/foodbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaSimulateRoute = ApiPublicMpesaSimulateRouteImport.update({
  id: '/api/public/mpesa/simulate',
  path: '/api/public/mpesa/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/foodbox': typeof FoodboxRoute
  '/onboarding': typeof OnboardingRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/mpesa/simulate': typeof ApiPublicMpesaSimulateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/foodbox': typeof FoodboxRoute
  '/onboarding': typeof OnboardingRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/mpesa/simulate': typeof ApiPublicMpesaSimulateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/foodbox': typeof FoodboxRoute
  '/onboarding': typeof OnboardingRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/mpesa/simulate': typeof ApiPublicMpesaSimulateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/foodbox'
    | '/onboarding'
    | '/api/public/mpesa/callback'
    | '/api/public/mpesa/simulate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/foodbox'
    | '/onboarding'
    | '/api/public/mpesa/callback'
    | '/api/public/mpesa/simulate'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/foodbox'
    | '/onboarding'
    | '/api/public/mpesa/callback'
    | '/api/public/mpesa/simulate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  FoodboxRoute: typeof FoodboxRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
  ApiPublicMpesaSimulateRoute: typeof ApiPublicMpesaSimulateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foodbox': {
      id: '/foodbox'
      path: '/foodbox'
      fullPath: '/foodbox'
      preLoaderRoute: typeof FoodboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/simulate': {
      id: '/api/public/mpesa/simulate'
      path: '/api/public/mpesa/simulate'
      fullPath: '/api/public/mpesa/simulate'
      preLoaderRoute: typeof ApiPublicMpesaSimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  FoodboxRoute: FoodboxRoute,
  OnboardingRoute: OnboardingRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
  ApiPublicMpesaSimulateRoute: ApiPublicMpesaSimulateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
